Homework5
ermekbaeva/MeerimErmekbaeva pull request #5
Opened 2021-11-08 09:36 UTC by ermekbaeva

Homework 5

2021-11-11 10:27 UTC, ZeroShadows requested changes

2021-11-11 11:18 UTC, ermekbaeva commented on src/test/java/com/epam/tc/hw5/cucumber/page/AbstractBasePage.java
> +        try {
Property Reader was moved into BaseTest

2021-11-14 18:40 UTC, ZeroShadows approved these changes

2021-11-14 18:40 UTC, ZeroShadows approved these changes

2021-11-14 18:41 UTC, ZeroShadows approved these changes

2021-11-15 11:13 UTC, merged