Homework7
ermekbaeva/MeerimErmekbaeva pull request #7
Opened 2021-11-17 11:54 UTC by ermekbaeva

homework7 done

2021-11-25 18:08 UTC, cold-flame requested changes

2021-11-26 11:11 UTC, ermekbaeva commented on src/test/java/com/epam/tc/hw7/tests/JdiPageTest.java
> +        assertThat(summaryResult.getText()).containsIgnoringCase(String.valueOf(data.getSum()));
Custom verify was used

2021-11-26 11:11 UTC, ermekbaeva commented on src/test/java/com/epam/tc/hw7/TestInit.java
> +        login();
parameter was added in method login()

2021-11-26 11:12 UTC, ermekbaeva commented on src/main/java/com/epam/tc/hw7/sections/MetalsAndColorsForm.java
> +    public void selectElements(List<String> value) {
this part was fixed

2021-11-26 11:13 UTC, ermekbaeva commented on src/main/java/com/epam/tc/hw7/pages/JdiSite.java
> +    @UI("img#user-icon") public static Link userIcon;
remove all variables to HomePage and MetalColorsPage

2021-11-26 11:13 UTC, ermekbaeva commented on src/main/java/com/epam/tc/hw7/pages/JdiSite.java
> +    @UI("#submit-button") public static Button submitButton;
this part was fixed

2021-11-30 17:09 UTC, cold-flame approved these changes

2021-12-01 10:41 UTC, merged